### ISSUE TITLE
design: 초대장 수정 페이지 레이아웃

### ISSUE THREAD

**Issue by cuconveniencestore** [livable-final/client#106]
##  📌 기능
- 초대장 수정 페이지 레이아웃
- 초대장 수정 페이지 바텀시트 레이아웃 및 연결
<img width="255" alt="image" src="https://github.com/livable-final/client/assets/125563995/1c19cff6-bb01-4625-9306-1ea2a6fe9568">
<img width="255" alt="image" src="https://github.com/livable-final/client/assets/125563995/4d7c5a26-220a-4e27-8df8-e9e68168ea19">

## 🪴 TODO
- [ ] 초대장 수정 페이지 레이아웃
- [ ] 초대장 수정 페이지 바텀시트 레이아웃
- [ ] 초대장 수정 + 바텀시트 연결
- [ ] 초대 목록 수정하기 바텀시트 + 초대장 수정 페이지 연결
