### ISSUE TITLE
feat: 홈 기능 추가

### ISSUE THREAD

**Issue by kledyu** [livable-final/client#110]
##  📌 기능
<img width="387" alt="image" src="https://github.com/livable-final/client/assets/83483378/ba6cc6ab-5480-4f5b-abd7-9cc3016e3f32">

## 🪴 TODO
- [ ] bnb 글자에도 동적으로 색상 변경
- [ ] 아이콘 업데이트 사항 추가
- [ ] 달력 바로가기 연결
- [ ] 구내식당 토글 On
