### ISSUE TITLE
refactor: 초대장 생성 플로우 전체적인 리팩토링

### ISSUE THREAD

**Issue by dev-junehee** [livable-final/client#121]
##  📌 기능
- API 연결 전 자잘하게 수정된 부분 반영

## 🪴 TODO
- [x] 바텀시트 타이틀 정렬
- [x] 뒤로가기 구현
- [x] 초대날짜/시간 선택 바텀시트 수정 -> 기능 연결하면서 추가 수정 필요!
- [x] 라디오 버튼 컴포넌트 수정
- [x] 이름/비밀번호 validation, error-message
- [x] 데이터에 따른 버튼 활성/비활성화 여부 체크
