### ISSUE TITLE
feat: 방문증 메인 페이지 api 연동

### ISSUE THREAD

**Issue by cuconveniencestore** [livable-final/client#136]
##  📌 기능
-   방문증 메인 페이지 api 연동
<img width="423" alt="image" src="https://github.com/livable-final/client/assets/125563995/87a07d52-4b7b-464d-b16d-2a4aa6d4eb78">

## 🪴 TODO
- [x] 방문증 기본정보 응답 api 연동
- [ ] 임시출입증 발급 api 연동
- [x] 빌딩 주변 카페 응답 api 연동
- [x] 빌딩 주변 식당 응답 api 연동
