### ISSUE TITLE
feat: 예약 가능 시간 API, 초대장 저장 API

### ISSUE THREAD

**Issue by dev-junehee** [livable-final/client#156]
##  📌 기능
-   

## 🪴 TODO
- [ ] 예약 가능 시간 API 수정 버전 확인
- [ ] 초대장 최종 저장 API 연결
- [ ] 방문 목적 컴포넌트 내 '예시' 기능 추가
