### ISSUE TITLE
feat: 점메추 룰렛 프로토타입

### ISSUE THREAD

**Issue by kledyu** [livable-final/client#16]
##  📌 기능
<img width="338" alt="image" src="https://github.com/livable-final/client/assets/83483378/052b6ae2-e72e-4457-bdf7-59c52a5625c4">

## 🪴 TODO
- [ ] 카테고리, 메뉴명 더미 데이터 제작
- [ ] 카테고리 메뉴 랜덤하게 룰렛 동작
- [ ] 카테고리 고정 후 메뉴 룰렛 동작

## 💡 참고 자료

https://ton-ton.tistory.com/7
