### ISSUE TITLE
refactor: 오늘 점심 Api Path 변경 및 리팩토링

### ISSUE THREAD

**Issue by kledyu** [livable-final/client#168]
##  📌 기능
-   

## 🪴 TODO
- [ ] 특정 메뉴를 판매하는 식당 응답 API PATH 변경
- [ ] 가장 많이 선택한 메뉴 10위 API PATH 변경
- [ ] fetch error 정의
