### ISSUE TITLE
fix: 초대장 생성 파트 오류 수정, 디자인 수정

### ISSUE THREAD

**Issue by dev-junehee** [livable-final/client#176]
##  📌 기능
-

## 🪴 TODO
- [x] 공용 컴포넌트 스타일 수정 (Add, Button, Category, Input)
- [x] 선택 가능 / 불가능 텍스트 추가
- [x] 버튼, 컴포넌트 컨테이너 반응형 수정
