### ISSUE TITLE
refactor: QA 수정사항 반영

### ISSUE THREAD

**Issue by dev-junehee** [livable-final/client#199]
##  📌 기능
- 초대장 생성

## 🪴 TODO
- [x] 바텀시트 오류 : 종일토글 on/off시 바텀시트 상단 잘림 현상 확인
- [x] 시간 선택 오류 : 시작과 끝을 선택했을 때 중간 선택 로직
- [x] 날짜 표기 방법 수정 : startDate, endDate가 같을 경우 날짜를 하루로 표기
- [x] 초대장 전송 후 의도하지 않은 Alert 오류 확인
- [x] 초대장 보내기 버튼 활성화/비활성화 예외처리
- [x] 데이트 픽커 최대 사이즈일 때(tab view) 선택 영역 스타일 수정
