### ISSUE TITLE
refactor: 외식 - 최근 검색 내역 수정

### ISSUE THREAD

**Issue by ChoEun-Sang** [livable-final/client#205]
##  📌 기능
-  최근 검색 내역 저장
-  최근 검색 내역 삭제
-  최근 검색 내역으로 검색

## 🪴 TODO
- [x] 최근 검색 내역 저장
- [x] 최근 검색 내역 삭제
- [x] 최근 검색 내역으로 검색
