### ISSUE TITLE
refactor: 달력 페이지 스타일 수정 및 리뷰 페이지 반응형 수정

### ISSUE THREAD

**Issue by ChoEun-Sang** [livable-final/client#223]
##  📌 기능
-  달력 페이지 스타일 수정 
- 리뷰 페이지 반응형 스타일 수정
- 바텀시트 조건 추가

## 🪴 TODO
- [x] 달력 페이지 스타일 수정 
- [x] 리뷰 페이지 반응형 스타일 수정
- [x] 바텀시트 조건 추가
