### ISSUE TITLE
fix: 초대장 발송 완료 페이지 수정

### ISSUE THREAD

**Issue by cuconveniencestore** [livable-final/client#224]
##  📌 기능
플로우 오류들 수정

## 🪴 TODO
- [x] 초대장 발송 완료 페이지 오류 수정
- [x] 초대장 다시 보내기 발송 완료 레이아웃 수정
- [x] 초대목록 삭제 후 리 랜더링 오류 수정
