### ISSUE TITLE
feat: 하나의 view 페이지에서 여러 컴포넌트 랜더링

### ISSUE THREAD

**Issue by jinu6262** [livable-final/client#33]
##  📌 기능
-   store를 활용하여 url변경 없이 여러 페이지 컴포넌트 랜더링

## 🪴 TODO
- [ ] 페이지 전환을 위한 store 작성
- [ ] ViewForm 에서 페이지 구분
- [ ] test 페이지 작성

## 💡 참고 자료
https://github.com/livable-final/client/wiki/%EA%B3%B5%EC%9C%A0
