### ISSUE TITLE
feat: 방문자 초대장 생성 플로우로 컴포넌트 렌더링 연결

### ISSUE THREAD

**Issue by dev-junehee** [livable-final/client#59]
##  📌 기능
-  방문자 초대장 생성 플로우 완성

## 🪴 TODO
- [x] 상단 헤더 고정
- [x] 버튼 고정 해제 후 각 컴포넌트 내부에 추가
- [x] Zustand를 활용하여 NextComponent 연결
