### ISSUE TITLE
design: 홈 파트 UI 작업

### ISSUE THREAD

**Issue by kledyu** [livable-final/client#68]
##  📌 기능
-   홈(리디자인)파트 UI 작업

## 🪴 TODO
- [ ] weather API 연동
- [ ] reviewPhoto 이미지 백엔드 분들과 논의 필요
- [ ] 구내식당 유/무에 따른 렌더 변화 필요

## 💡 참고 자료
<img width="296" alt="image" src="https://github.com/livable-final/client/assets/83483378/57222fc2-a9c0-4ec3-8c70-fef8543e87f7">
