### ISSUE TITLE
design: Input box 제작

### ISSUE THREAD

**Issue by cuconveniencestore** [livable-final/client#8]
##  📌 기능
-   초대장 발송 페이지 내 사용되는 Input text box 제작

## 🪴 TODO
- [ ] input text box 제작
- [ ] input text icon box 제작
- [ ] input sentence box 제작

## 💡 참고 자료
<img width="357" alt="image" src="https://github.com/livable-final/client/assets/125563995/9b04e95e-bf3a-4db2-a9c4-165f63ae95c8">
<img width="344" alt="image" src="https://github.com/livable-final/client/assets/125563995/a7abac5d-dcd9-4c01-84ea-5482b77493c0">
<img width="271" alt="image" src="https://github.com/livable-final/client/assets/125563995/e65b836d-ebdd-4635-8c26-67ac12e0d500">
